use_react_native!(
    :path => config[:reactNativePath],
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  # Add Firebase pods
  pod 'Firebase/Analytics'
  pod 'Firebase/Crashlytics'
  
  # Add Google Mobile Ads
  pod 'Google-Mobile-Ads-SDK'
  
  # Permissions
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-AppTrackingTransparency', :path => "#{permissions_path}/AppTrackingTransparency"
  
  # Vector Icons
  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'